image: node:12-alpine

stages: 
  - install
  - build
  - config
  - upload

install-packages:
  stage: install
  script:
    - echo "Installing packages..."
    - npm install
    - echo "Install complete."

build:
  stage: build
  script:
    - echo "Starting to compile the code..."
    - npm run build
    - ls
    - echo "Compile complete."

config-s3:
  stage: config
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - echo "Starting to configure the access to AWS"
    - aws configure set region us-east-1
    - echo "Configuration complete."

upload-s3:
  stage: upload
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - echo "Starting to upload the files to s3 bucket"
    - aws s3 cp build/css s3://$S3_BUCKET/
    - echo "Configuration complete."
